# Generated by Django 4.1.2 on 2022-10-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='institution_number',
            new_name='inst_num',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='transit_number',
            new_name='transit_num',
        ),
    ]
