# Generated by Django 4.1.2 on 2022-10-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_rename_institution_number_bank_inst_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='branches',
            field=models.ManyToManyField(to='banks.branch'),
        ),
    ]
