# Generated by Django 4.1.2 on 2022-11-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_bank_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
